#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(dirname -- "$(realpath -- "${BASH_SOURCE[0]}")")"
ROOTFS_OUT="$SCRIPT_DIR/../build/tmp/deploy/images/jetson-orin-nano-devkit-nvme/demo-image-base-jetson-orin-nano-devkit-nvme.rootfs.tar.gz"
DEFAULT_BASE="/srv/pxe"

DEFAULT_DOMAIN="pxe.local"
DEFAULT_DNS="8.8.8.8, 8.8.4.4"
DEFAULT_LEASE="600"
DEFAULT_MAX_LEASE="7200"

UEFI_FILENAME="bootaa64.efi"


if [ "$(id -u)" -ne 0 ]; then
  echo "Error: This script must be run as root (sudo)."
  echo "Run: sudo $0"
  exit 1
fi

if [ ! -f "$ROOTFS_OUT" ]; then
  echo "Error: Root filesystem archive not found at $ROOTFS_OUT"
  exit 1
fi

detect_default_ifname() {
  ip route show default 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="dev") {print $(i+1); exit}}'
}

detect_iface_cidr() {
  local ifname="$1"
  ip -4 -o addr show dev "$ifname" 2>/dev/null | awk '{print $4; exit}'
}

calc_net_info() {
  local cidr="$1"
  python3 - <<'PY'
import ipaddress, os
cidr = os.environ["CIDR"]
net = ipaddress.ip_network(cidr, strict=False)
network = str(net.network_address)
netmask = str(net.netmask)
broadcast = str(net.broadcast_address)

# Suggest DHCP range: network+100 .. network+200 (clamped inside host range)
hosts = list(net.hosts())
if len(hosts) >= 2:
    def clamp_index(i):
        if i < 0: return 0
        if i >= len(hosts): return len(hosts) - 1
        return i
    start = hosts[clamp_index(99)]   # +100th host (0-based)
    end   = hosts[clamp_index(199)]  # +200th host
else:
    start = end = ""

print(network)
print(netmask)
print(broadcast)
print(str(start) if start else "")
print(str(end) if end else "")
PY
}

require_pkg() {
  local pkg="$1"
  if ! dpkg -s "$pkg" >/dev/null 2>&1; then
    apt-get update
    apt-get install -y "$pkg"
  fi
}

extract_rootfs() {
  local archive_path="$1"
  local target_dir="$2"

  echo "Extracting root filesystem from $archive_path to $target_dir..."
  mkdir -p "$target_dir"
  tar -xzf "$archive_path" -C "$target_dir"
  echo "Extraction complete."
}

setup_exports() {
  local rootfs_dir="$1"
  local export_client_cidr="$2"

  local exports_file="/etc/exports"
  local backup_file="/etc/exports.bak.$(date +%Y%m%d%H%M%S)"

  local opts="rw,sync,no_subtree_check,no_root_squash,insecure"
  local export_line="${rootfs_dir} ${export_client_cidr}(${opts})"

  echo "Configuring NFS exports..."
  echo "  ROOTFS_DIR: $rootfs_dir"
  echo "  CLIENTS:    $export_client_cidr"
  echo "  LINE:       $export_line"

  require_pkg "nfs-kernel-server"

  if [ -f "$exports_file" ]; then
    cp -a "$exports_file" "$backup_file"
    echo "Backed up $exports_file to $backup_file"
  fi

  rm -f "$exports_file"
  cat > "$exports_file" <<EOF
# Generated by pxe-setup.sh on $(date -Is)
$export_line
EOF
  chmod 644 "$exports_file"

  exportfs -ra
  systemctl restart nfs-kernel-server

  echo "NFS exports applied."
}

setup_tftp() {
  local tftp_dir="$1"
  local rootfs_dir="$2"
  local ip_server="$3"

  local TFTP_USERNAME="tftp"
  local TFTP_ADDRESS=":69"
  local TFTP_OPTIONS="--secure --verbose --verbosity 5"

  echo "Setting up TFTP..."
  echo "  TFTP_DIR: $tftp_dir"

  require_pkg "tftpd-hpa"

  if ! id "$TFTP_USERNAME" >/dev/null 2>&1; then
    useradd --system --no-create-home --shell /usr/sbin/nologin "$TFTP_USERNAME"
  fi

  mkdir -p "$tftp_dir"
  chown -R "$TFTP_USERNAME:$TFTP_USERNAME" "$tftp_dir"
  chmod 755 "$tftp_dir"

  cat > /etc/default/tftpd-hpa <<EOF
# /etc/default/tftpd-hpa
TFTP_USERNAME="${TFTP_USERNAME}"
TFTP_DIRECTORY="${tftp_dir}"
TFTP_ADDRESS="${TFTP_ADDRESS}"
TFTP_OPTIONS="${TFTP_OPTIONS}"
EOF

  local EFI_DIR="$rootfs_dir/EFI/BOOT"
  if [ -f "$EFI_DIR/firstLoader.efi" ]; then
    cp -f "$EFI_DIR/firstLoader.efi" "$tftp_dir/bootaa64.efi"
  else
    echo "Warning: Missing $EFI_DIR/firstLoader.efi (skip)"
  fi

  if [ -f "$EFI_DIR/secondLoader.enc" ]; then
    cp -f "$EFI_DIR/secondLoader.enc" "$tftp_dir/"
  else
    echo "Warning: Missing $EFI_DIR/secondLoader.enc (skip)"
  fi

  if [ -f "$rootfs_dir/boot/Image" ]; then
    cp -f "$rootfs_dir/boot/Image" "$tftp_dir/"
  else
    echo "Warning: Missing $rootfs_dir/boot/Image (skip)"
  fi

  if [ -f "$rootfs_dir/boot/initrd" ]; then
    cp -f "$rootfs_dir/boot/initrd" "$tftp_dir/"
  else
    echo "Warning: Missing $rootfs_dir/boot/initrd (skip)"
  fi

  cat > "$tftp_dir/cmdline.txt" <<EOF
root=/dev/nfs nfsroot=${ip_server}:${rootfs_dir} nfsopts=vers=3,tcp,nolock ip=dhcp net.ifnames=0
console=ttyTCU0,115200 firmware_class.path=/etc/firmware
EOF

  systemctl daemon-reload
  systemctl enable --now tftpd-hpa
  systemctl restart tftpd-hpa

  echo "TFTP setup complete."
}

setup_dhcp_server() {
  local ifname="$1"
  local subnet_network="$2"
  local subnet_mask="$3"
  local broadcast_addr="$4"
  local dhcp_start="$5"
  local dhcp_end="$6"
  local router_ip="$7"
  local next_server_ip="$8"
  local dns_servers="$9"
  local domain_name="${10}"
  local default_lease="${11}"
  local max_lease="${12}"
  local pxe_filename="${13}"

  echo "Setting up DHCP server..."
  echo "  IFACE:   $ifname"
  echo "  SUBNET:  $subnet_network / $subnet_mask"
  echo "  RANGE:   $dhcp_start - $dhcp_end"
  echo "  ROUTER:  $router_ip"
  echo "  NEXT:    $next_server_ip"
  echo "  FILE:    $pxe_filename"

  require_pkg "isc-dhcp-server"

  cat > /etc/default/isc-dhcp-server <<EOF
INTERFACESv4="$ifname"
EOF

  cat > /etc/dhcp/dhcpd.conf <<EOF
option domain-name "${domain_name}";
option domain-name-servers ${dns_servers};
default-lease-time ${default_lease};
max-lease-time ${max_lease};
authoritative;

subnet ${subnet_network} netmask ${subnet_mask} {
    range ${dhcp_start} ${dhcp_end};
    option routers ${router_ip};
    option broadcast-address ${broadcast_addr};
    option domain-name-servers ${dns_servers};

    next-server ${next_server_ip};
    filename "${pxe_filename}";
}
EOF

  dhcpd -t -cf /etc/dhcp/dhcpd.conf
  systemctl enable --now isc-dhcp-server
  systemctl restart isc-dhcp-server

  echo "DHCP setup complete."
}


DEFAULT_IFNAME="$(detect_default_ifname || true)"
read -r -p "Enter network interface [${DEFAULT_IFNAME}]: " IFNAME
IFNAME="${IFNAME:-$DEFAULT_IFNAME}"
if [ -z "${IFNAME:-}" ]; then
  echo "Error: Cannot detect interface. Please set IFNAME."
  exit 1
fi

DEFAULT_CIDR="$(detect_iface_cidr "$IFNAME" || true)"
read -r -p "Enter server IPv4 CIDR on ${IFNAME} (e.g. 192.168.42.1/24) [${DEFAULT_CIDR}]: " IP_CIDR
IP_CIDR="${IP_CIDR:-$DEFAULT_CIDR}"
if [ -z "${IP_CIDR:-}" ]; then
  echo "Error: No IPv4 CIDR found on interface ${IFNAME}. Configure IP first."
  exit 1
fi

IP_SERVER="${IP_CIDR%%/*}"

CIDR="$IP_CIDR"
export CIDR
readarray -t NETINFO < <(calc_net_info "$CIDR")
SUBNET_NETWORK="${NETINFO[0]}"
SUBNET_MASK="${NETINFO[1]}"
BROADCAST_ADDR="${NETINFO[2]}"
SUGGEST_DHCP_START="${NETINFO[3]}"
SUGGEST_DHCP_END="${NETINFO[4]}"
SUBNET_CIDR="${SUBNET_NETWORK}/${IP_CIDR##*/}"

# Allow override
read -r -p "Subnet CIDR for clients (NFS export & reference) [${SUBNET_CIDR}]: " SUBNET
SUBNET="${SUBNET:-$SUBNET_CIDR}"

read -r -p "DHCP range start [${SUGGEST_DHCP_START}]: " DHCP_START
DHCP_START="${DHCP_START:-$SUGGEST_DHCP_START}"

read -r -p "DHCP range end   [${SUGGEST_DHCP_END}]: " DHCP_END
DHCP_END="${DHCP_END:-$SUGGEST_DHCP_END}"

read -r -p "Router/Gateway IP [${IP_SERVER}]: " ROUTER_IP
ROUTER_IP="${ROUTER_IP:-$IP_SERVER}"

read -r -p "DNS servers (comma-separated) [${DEFAULT_DNS}]: " DNS_SERVERS
DNS_SERVERS="${DNS_SERVERS:-$DEFAULT_DNS}"

read -r -p "Domain name [${DEFAULT_DOMAIN}]: " DOMAIN_NAME
DOMAIN_NAME="${DOMAIN_NAME:-$DEFAULT_DOMAIN}"


read -r -p "Enter PXE base directory [${DEFAULT_BASE}]: " BASE_DIR
BASE_DIR="${BASE_DIR:-$DEFAULT_BASE}"

TFTP_DIR="$BASE_DIR/tftp"
ROOTFS_DIR="$BASE_DIR/rootfs"

mkdir -p "$TFTP_DIR" "$ROOTFS_DIR"
echo "Using TFTP_DIR=$TFTP_DIR"
echo "Using ROOTFS_DIR=$ROOTFS_DIR"
echo "Using IFNAME=$IFNAME, IP_SERVER=$IP_SERVER, SUBNET=$SUBNET"

extract_rootfs "$ROOTFS_OUT" "$ROOTFS_DIR"
setup_exports "$ROOTFS_DIR" "$SUBNET"
setup_tftp "$TFTP_DIR" "$ROOTFS_DIR" "$IP_SERVER"
setup_dhcp_server \
  "$IFNAME" \
  "$SUBNET_NETWORK" \
  "$SUBNET_MASK" \
  "$BROADCAST_ADDR" \
  "$DHCP_START" \
  "$DHCP_END" \
  "$ROUTER_IP" \
  "$IP_SERVER" \
  "$DNS_SERVERS" \
  "$DOMAIN_NAME" \
  "$DEFAULT_LEASE" \
  "$DEFAULT_MAX_LEASE" \
  "$UEFI_FILENAME"

echo "PXE setup complete."
