header:
  version: 14

distro: poky
target:
  - core-image-minimal

repos:
  # openembedded-core:
  #   path: repos/openembedded-core
  #   url: git://git.openembedded.org/openembedded-core.git
  #   layers:
  #     meta: disabled

  bitbake:
    path: repos/bitbake
    url: git://git.openembedded.org/bitbake.git
    branch: "2.8"
    layers:
      .: disabled

  meta-openembedded:
    url: https://git.openembedded.org/meta-openembedded
    path: repos/meta-openembedded
    layers:
      meta-oe:
      meta-python:
      meta-networking:
      meta-filesystems:

  poky:
    url: git://git.yoctoproject.org/poky.git
    path: repos/poky
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp: